### ISSUE TITLE
Support unicode in team name

### ISSUE THREAD

**Issue by rkkautsar** [CTFd/CTFd#315]
Current deployment option using docker-compose uses default MySQL (MariaDB) encoding, which in my case is not UTF8. Specifying a cnf file would solve this problem, see [related SO answer](https://stackoverflow.com/a/3513812) and *Using a custom MySQL configuration file* section of [mariadb dockerhub description](https://hub.docker.com/_/mariadb/)

Related error message example:
```
InternalError: (pymysql.err.InternalError) (1267, u"Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8mb4_general_ci,COERCIBLE) for operation '='") [SQL: u'SELECT teams.id AS teams_id, teams.name AS teams_name, teams.email AS teams_email, teams.password AS teams_password, teams.website AS teams_website, teams.affiliation AS teams_affiliation, teams.country AS teams_country, teams.bracket AS teams_bracket, teams.banned AS teams_banned, teams.verified AS teams_verified, teams.`admin` AS teams_admin, teams.joined AS teams_joined, name \nFROM teams \nWHERE teams.name = %(name_1)s \n LIMIT %(param_1)s'] [parameters: {u'name_1': u"(\u0e07'\u0300-'\u0301)\u0e07", u'param_1': 1}]
```

**Comment by rkkautsar** [comment]
Hmm I've just seen #282 but why is this issue occurs to me?

**Comment by ColdHeat** [comment]
Are you upgrading your database from a previous version of CTFd? The lack of unicode support in MySQL should be resolved.

**Comment by rkkautsar** [comment]
Yes, I've created new database after pulling from master, fresh docker build, and I still can't register team name with unicode.

Complete error.log:
```
[2017-07-16 05:20:32 +0000] [22] [INFO] Starting gunicorn 19.7.0
[2017-07-16 05:20:32 +0000] [22] [INFO] Listening at: http://0.0.0.0:8000 (22)
[2017-07-16 05:20:32 +0000] [22] [INFO] Using worker: sync
[2017-07-16 05:20:32 +0000] [32] [INFO] Booting worker with pid: 32
[2017-07-16 05:22:32 +0000] [11] [INFO] Starting gunicorn 19.7.0
[2017-07-16 05:22:32 +0000] [11] [INFO] Listening at: http://0.0.0.0:8000 (11)
[2017-07-16 05:22:32 +0000] [11] [INFO] Using worker: sync
[2017-07-16 05:22:32 +0000] [21] [INFO] Booting worker with pid: 21
[2017-07-16 05:23:15,516] ERROR in app: Exception on /register [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/CTFd/CTFd/auth.py", line 116, in register
    names = Teams.query.add_columns('name', 'id').filter_by(name=name).first()
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2755, in first
    ret = list(self[0:1])
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2547, in __getitem__
    return list(res)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2855, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2878, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python2.7/site-packages/pymysql/cursors.py", line 166, in execute
    result = self._query(query)
  File "/usr/local/lib/python2.7/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 856, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 1057, in _read_query_result
    result.read()
  File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 1340, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 1014, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 393, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python2.7/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
InternalError: (pymysql.err.InternalError) (1267, u"Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8mb4_general_ci,COERCIBLE) for operation '='") [SQL: u'SELECT teams.id AS teams_id, teams.name AS teams_name, teams.email AS teams_email, teams.password AS teams_password, teams.website AS teams_website, teams.affiliation AS teams_affiliation, teams.country AS teams_country, teams.bracket AS teams_bracket, teams.banned AS teams_banned, teams.verified AS teams_verified, teams.`admin` AS teams_admin, teams.joined AS teams_joined, name, id \nFROM teams \nWHERE teams.name = %(name_1)s \n LIMIT %(param_1)s'] [parameters: {u'name_1': u"(\u0e07'\u0300-'\u0301)\u0e07", u'param_1': 1}]
```

Completely reproducible in my machine

**Comment by ColdHeat** [comment]
Okay can you check what the charset is on your database? 

I believe this should work:
```
USE ctfd;
SELECT @@character_set_database;
```

I believe the issue is that the `docker-compose.yml` file specifies the database which is created but it is not created with the proper charset.

**Comment by ColdHeat** [comment]
@rkkautsar Nothing I can do for your current database from my end but this should be fixed now if you pull, clear your `.data` folder, and rebuild. 

If it's not fixed, feel free to reopen.
